# Generated by Django 5.1.1 on 2024-10-07 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farm_market", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryCrew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contact_info", models.CharField(max_length=255)),
                (
                    "assigned_orders",
                    models.ManyToManyField(
                        blank=True,
                        related_name="delivery_crews",
                        to="farm_market.order",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_crew",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="farm_market.deliverycrew",
            ),
        ),
    ]
