# Generated by Django 5.1.2 on 2024-10-14 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("farm_market", "0003_product_category_product_composition_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="name",
            new_name="title",
        ),
    ]
