# Generated by Django 5.1.2 on 2024-10-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farm_market", "0005_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="region",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="zip_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
